In [1]:
from processes import *

Processes = [
    Process(pid=1, arrival_time=0, burst_time=10, priority=3),
    Process(pid=2, arrival_time=2, burst_time=4, priority=3),
    Process(pid=3, arrival_time=4, burst_time=8, priority=2),
    Process(pid=4, arrival_time=6, burst_time=6, priority=1),
    Process(pid=5, arrival_time=8, burst_time=1, priority=1),
    Process(pid=6, arrival_time=100, burst_time=12, priority=3),
    Process(pid=7, arrival_time=1, burst_time=5, priority=0)]

scheduler = PriorityScheduler(Processes, preemptive=False)


# \\scheduler.schedule()



# scheduler = FIFSscheduler(Processes)
# scheduler.schedule()
scheduler = RRscheduler(Processes,2)
scheduler.schedule()

Time 0: Checking for arriving processes...
Ready Queue: [1]
Running Process: 1
Time 0: Running Process 1 (Remaining Time: 9)
Time 1: Checking for arriving processes...
Ready Queue: [7]
Running Process: 1
Time 1: Running Process 1 (Remaining Time: 8)
Time 2: Checking for arriving processes...
Ready Queue: [7, 1, 2]
Running Process: 7
Time 2: Running Process 7 (Remaining Time: 4)
Time 3: Checking for arriving processes...
Ready Queue: [1, 2]
Running Process: 7
Time 3: Running Process 7 (Remaining Time: 3)
Time 4: Checking for arriving processes...
Ready Queue: [1, 2, 7, 3]
Running Process: 1
Time 4: Running Process 1 (Remaining Time: 7)
Time 5: Checking for arriving processes...
Ready Queue: [2, 7, 3]
Running Process: 1
Time 5: Running Process 1 (Remaining Time: 6)
Time 6: Checking for arriving processes...
Ready Queue: [2, 7, 3, 1, 4]
Running Process: 2
Time 6: Running Process 2 (Remaining Time: 3)
Time 7: Checking for arriving processes...
Ready Queue: [7, 3, 1, 4]
Running Process: 2
Time 7: Running Process 2 (Remaining Time: 2)
Time 8: Checking for arriving processes...
Ready Queue: [7, 3, 1, 4, 2, 5]
Running Process: 7
Time 8: Running Process 7 (Remaining Time: 2)
Time 9: Checking for arriving processes...
Ready Queue: [3, 1, 4, 2, 5]
Running Process: 7
Time 9: Running Process 7 (Remaining Time: 1)
Time 10: Checking for arriving processes...
Ready Queue: [3, 1, 4, 2, 5, 7]
Running Process: 3
Time 10: Running Process 3 (Remaining Time: 7)
Time 11: Checking for arriving processes...
Ready Queue: [1, 4, 2, 5, 7]
Running Process: 3
Time 11: Running Process 3 (Remaining Time: 6)
Time 12: Checking for arriving processes...
Ready Queue: [1, 4, 2, 5, 7, 3]
Running Process: 1
Time 12: Running Process 1 (Remaining Time: 5)
Time 13: Checking for arriving processes...
Ready Queue: [4, 2, 5, 7, 3]
Running Process: 1
Time 13: Running Process 1 (Remaining Time: 4)
Time 14: Checking for arriving processes...
Ready Queue: [4, 2, 5, 7, 3, 1]
Running Process: 4
Time 14: Running Process 4 (Remaining Time: 5)
Time 15: Checking for arriving processes...
Ready Queue: [2, 5, 7, 3, 1]
Running Process: 4
Time 15: Running Process 4 (Remaining Time: 4)
Time 16: Checking for arriving processes...
Ready Queue: [2, 5, 7, 3, 1, 4]
Running Process: 2
Time 16: Running Process 2 (Remaining Time: 1)
Time 17: Checking for arriving processes...
Ready Queue: [5, 7, 3, 1, 4]
Running Process: 2
Time 17: Running Process 2 (Remaining Time: 0)
Time 18: Checking for arriving processes...
Ready Queue: [5, 7, 3, 1, 4]
Running Process: 5
Time 18: Running Process 5 (Remaining Time: 0)
Time 19: Checking for arriving processes...
Ready Queue: [7, 3, 1, 4]
Running Process: 7
Time 19: Running Process 7 (Remaining Time: 0)
Time 20: Checking for arriving processes...
Ready Queue: [3, 1, 4]
Running Process: 3
Time 20: Running Process 3 (Remaining Time: 5)
Time 21: Checking for arriving processes...
Ready Queue: [1, 4]
Running Process: 3
Time 21: Running Process 3 (Remaining Time: 4)
Time 22: Checking for arriving processes...
Ready Queue: [1, 4, 3]
Running Process: 1
Time 22: Running Process 1 (Remaining Time: 3)
Time 23: Checking for arriving processes...
Ready Queue: [4, 3]
Running Process: 1
Time 23: Running Process 1 (Remaining Time: 2)
Time 24: Checking for arriving processes...
Ready Queue: [4, 3, 1]
Running Process: 4
Time 24: Running Process 4 (Remaining Time: 3)
Time 25: Checking for arriving processes...
Ready Queue: [3, 1]
Running Process: 4
Time 25: Running Process 4 (Remaining Time: 2)
Time 26: Checking for arriving processes...
Ready Queue: [3, 1, 4]
Running Process: 3
Time 26: Running Process 3 (Remaining Time: 3)
Time 27: Checking for arriving processes...
Ready Queue: [1, 4]
Running Process: 3
Time 27: Running Process 3 (Remaining Time: 2)
Time 28: Checking for arriving processes...
Ready Queue: [1, 4, 3]
Running Process: 1
Time 28: Running Process 1 (Remaining Time: 1)
Time 29: Checking for arriving processes...
Ready Queue: [4, 3]
Running Process: 1
Time 29: Running Process 1 (Remaining Time: 0)
Time 30: Checking for arriving processes...
Ready Queue: [4, 3]
Running Process: 4
Time 30: Running Process 4 (Remaining Time: 1)
Time 31: Checking for arriving processes...
Ready Queue: [3]
Running Process: 4
Time 31: Running Process 4 (Remaining Time: 0)
Time 32: Checking for arriving processes...
Ready Queue: [3]
Running Process: 3
Time 32: Running Process 3 (Remaining Time: 1)
Time 33: Checking for arriving processes...
Ready Queue: []
Running Process: 3
Time 33: Running Process 3 (Remaining Time: 0)
Time 34: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 35: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 36: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 37: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 38: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 39: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 40: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 41: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 42: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 43: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 44: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 45: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 46: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 47: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 48: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 49: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 50: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 51: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 52: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 53: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 54: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 55: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 56: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 57: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 58: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 59: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 60: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 61: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 62: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 63: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 64: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 65: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 66: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 67: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 68: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 69: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 70: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 71: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 72: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 73: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 74: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 75: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 76: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 77: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 78: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 79: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 80: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 81: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 82: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 83: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 84: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 85: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 86: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 87: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 88: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 89: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 90: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 91: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 92: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 93: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 94: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 95: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 96: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 97: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 98: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 99: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 100: Checking for arriving processes...
Ready Queue: [6]
Running Process: 6
Time 100: Running Process 6 (Remaining Time: 11)
Time 101: Checking for arriving processes...
Ready Queue: []
Running Process: 6
Time 101: Running Process 6 (Remaining Time: 10)
Time 102: Checking for arriving processes...
Ready Queue: [6]
Running Process: 6
Time 102: Running Process 6 (Remaining Time: 9)
Time 103: Checking for arriving processes...
Ready Queue: []
Running Process: 6
Time 103: Running Process 6 (Remaining Time: 8)
Time 104: Checking for arriving processes...
Ready Queue: [6]
Running Process: 6
Time 104: Running Process 6 (Remaining Time: 7)
Time 105: Checking for arriving processes...
Ready Queue: []
Running Process: 6
Time 105: Running Process 6 (Remaining Time: 6)
Time 106: Checking for arriving processes...
Ready Queue: [6]
Running Process: 6
Time 106: Running Process 6 (Remaining Time: 5)
Time 107: Checking for arriving processes...
Ready Queue: []
Running Process: 6
Time 107: Running Process 6 (Remaining Time: 4)
Time 108: Checking for arriving processes...
Ready Queue: [6]
Running Process: 6
Time 108: Running Process 6 (Remaining Time: 3)
Time 109: Checking for arriving processes...
Ready Queue: []
Running Process: 6
Time 109: Running Process 6 (Remaining Time: 2)
Time 110: Checking for arriving processes...
Ready Queue: [6]
Running Process: 6
Time 110: Running Process 6 (Remaining Time: 1)
Time 111: Checking for arriving processes...
Ready Queue: []
Running Process: 6
Time 111: Running Process 6 (Remaining Time: 0)

In [2]:

Processes = [
    # P1 arrives at the very beginning. With a long burst, it will definitely be preempted.
    Process(pid=1, arrival_time=0, burst_time=10, priority=2),
    
    # P2 and P3 arrive quickly after P1, stacking up the ready queue.
    Process(pid=2, arrival_time=1, burst_time=4, priority=1),
    Process(pid=3, arrival_time=2, burst_time=5, priority=3),
    
    # P4 has a very short burst. It's a good test to ensure your scheduler 
    # properly handles a process finishing before the time quantum expires.
    Process(pid=4, arrival_time=4, burst_time=2, priority=0),
    
    # P5 arrives exactly when a standard time quantum (like Q=4 or Q=5) might be triggering 
    # a context switch. This tests if your queue appends new arrivals before or after preempted processes.
    Process(pid=5, arrival_time=5, burst_time=8, priority=2),
    
    # P6 tests simultaneous arrival. If P5 gets preempted at t=10, and P6 arrives at t=10, 
    # your queue logic needs to decide who goes in first.
    Process(pid=6, arrival_time=10, burst_time=3, priority=1),
    
    # P7 tests CPU idle time. The CPU should completely drain the ready queue and sit idle 
    # for a while before this process arrives.
    Process(pid=7, arrival_time=50, burst_time=7, priority=3)
]
scheduler = RRscheduler(Processes,3)
scheduler.schedule()
scheduler.gantt_chart_array

Time 0: Checking for arriving processes...
Ready Queue: [1]
Running Process: 1
Time 0: Running Process 1 (Remaining Time: 9)
Time 1: Checking for arriving processes...
Ready Queue: [2]
Running Process: 1
Time 1: Running Process 1 (Remaining Time: 8)
Time 2: Checking for arriving processes...
Ready Queue: [2, 3]
Running Process: 1
Time 2: Running Process 1 (Remaining Time: 7)
Time 3: Checking for arriving processes...
Ready Queue: [2, 3, 1]
Running Process: 2
Time 3: Running Process 2 (Remaining Time: 3)
Time 4: Checking for arriving processes...
Ready Queue: [3, 1, 4]
Running Process: 2
Time 4: Running Process 2 (Remaining Time: 2)
Time 5: Checking for arriving processes...
Ready Queue: [3, 1, 4, 5]
Running Process: 2
Time 5: Running Process 2 (Remaining Time: 1)
Time 6: Checking for arriving processes...
Ready Queue: [3, 1, 4, 5, 2]
Running Process: 3
Time 6: Running Process 3 (Remaining Time: 4)
Time 7: Checking for arriving processes...
Ready Queue: [1, 4, 5, 2]
Running Process: 3
Time 7: Running Process 3 (Remaining Time: 3)
Time 8: Checking for arriving processes...
Ready Queue: [1, 4, 5, 2]
Running Process: 3
Time 8: Running Process 3 (Remaining Time: 2)
Time 9: Checking for arriving processes...
Ready Queue: [1, 4, 5, 2, 3]
Running Process: 1
Time 9: Running Process 1 (Remaining Time: 6)
Time 10: Checking for arriving processes...
Ready Queue: [4, 5, 2, 3, 6]
Running Process: 1
Time 10: Running Process 1 (Remaining Time: 5)
Time 11: Checking for arriving processes...
Ready Queue: [4, 5, 2, 3, 6]
Running Process: 1
Time 11: Running Process 1 (Remaining Time: 4)
Time 12: Checking for arriving processes...
Ready Queue: [4, 5, 2, 3, 6, 1]
Running Process: 4
Time 12: Running Process 4 (Remaining Time: 1)
Time 13: Checking for arriving processes...
Ready Queue: [5, 2, 3, 6, 1]
Running Process: 4
Time 13: Running Process 4 (Remaining Time: 0)
Time 14: Checking for arriving processes...
Ready Queue: [5, 2, 3, 6, 1]
Running Process: 5
Time 14: Running Process 5 (Remaining Time: 7)
Time 15: Checking for arriving processes...
Ready Queue: [2, 3, 6, 1]
Running Process: 5
Time 15: Running Process 5 (Remaining Time: 6)
Time 16: Checking for arriving processes...
Ready Queue: [2, 3, 6, 1]
Running Process: 5
Time 16: Running Process 5 (Remaining Time: 5)
Time 17: Checking for arriving processes...
Ready Queue: [2, 3, 6, 1, 5]
Running Process: 2
Time 17: Running Process 2 (Remaining Time: 0)
Time 18: Checking for arriving processes...
Ready Queue: [3, 6, 1, 5]
Running Process: 3
Time 18: Running Process 3 (Remaining Time: 1)
Time 19: Checking for arriving processes...
Ready Queue: [6, 1, 5]
Running Process: 3
Time 19: Running Process 3 (Remaining Time: 0)
Time 20: Checking for arriving processes...
Ready Queue: [6, 1, 5]
Running Process: 6
Time 20: Running Process 6 (Remaining Time: 2)
Time 21: Checking for arriving processes...
Ready Queue: [1, 5]
Running Process: 6
Time 21: Running Process 6 (Remaining Time: 1)
Time 22: Checking for arriving processes...
Ready Queue: [1, 5]
Running Process: 6
Time 22: Running Process 6 (Remaining Time: 0)
Time 23: Checking for arriving processes...
Ready Queue: [1, 5]
Running Process: 1
Time 23: Running Process 1 (Remaining Time: 3)
Time 24: Checking for arriving processes...
Ready Queue: [5]
Running Process: 1
Time 24: Running Process 1 (Remaining Time: 2)
Time 25: Checking for arriving processes...
Ready Queue: [5]
Running Process: 1
Time 25: Running Process 1 (Remaining Time: 1)
Time 26: Checking for arriving processes...
Ready Queue: [5, 1]
Running Process: 5
Time 26: Running Process 5 (Remaining Time: 4)
Time 27: Checking for arriving processes...
Ready Queue: [1]
Running Process: 5
Time 27: Running Process 5 (Remaining Time: 3)
Time 28: Checking for arriving processes...
Ready Queue: [1]
Running Process: 5
Time 28: Running Process 5 (Remaining Time: 2)
Time 29: Checking for arriving processes...
Ready Queue: [1, 5]
Running Process: 1
Time 29: Running Process 1 (Remaining Time: 0)
Time 30: Checking for arriving processes...
Ready Queue: [5]
Running Process: 5
Time 30: Running Process 5 (Remaining Time: 1)
Time 31: Checking for arriving processes...
Ready Queue: []
Running Process: 5
Time 31: Running Process 5 (Remaining Time: 0)
Time 32: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 33: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 34: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 35: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 36: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 37: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 38: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 39: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 40: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 41: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 42: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 43: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 44: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 45: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 46: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 47: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 48: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 49: Checking for arriving processes...
Ready Queue: []
Running Process: None
Time 50: Checking for arriving processes...
Ready Queue: [7]
Running Process: 7
Time 50: Running Process 7 (Remaining Time: 6)
Time 51: Checking for arriving processes...
Ready Queue: []
Running Process: 7
Time 51: Running Process 7 (Remaining Time: 5)
Time 52: Checking for arriving processes...
Ready Queue: []
Running Process: 7
Time 52: Running Process 7 (Remaining Time: 4)
Time 53: Checking for arriving processes...
Ready Queue: [7]
Running Process: 7
Time 53: Running Process 7 (Remaining Time: 3)
Time 54: Checking for arriving processes...
Ready Queue: []
Running Process: 7
Time 54: Running Process 7 (Remaining Time: 2)
Time 55: Checking for arriving processes...
Ready Queue: []
Running Process: 7
Time 55: Running Process 7 (Remaining Time: 1)
Time 56: Checking for arriving processes...
Ready Queue: [7]
Running Process: 7
Time 56: Running Process 7 (Remaining Time: 0)

[(0, 1),
 (1, 1),
 (2, 1),
 (3, 2),
 (4, 2),
 (5, 2),
 (6, 3),
 (7, 3),
 (8, 3),
 (9, 1),
 (10, 1),
 (11, 1),
 (12, 4),
 (13, 4),
 (14, 5),
 (15, 5),
 (16, 5),
 (17, 2),
 (18, 3),
 (19, 3),
 (20, 6),
 (21, 6),
 (22, 6),
 (23, 1),
 (24, 1),
 (25, 1),
 (26, 5),
 (27, 5),
 (28, 5),
 (29, 1),
 (30, 5),
 (31, 5),
 (50, 7),
 (51, 7),
 (52, 7),
 (53, 7),
 (54, 7),
 (55, 7),
 (56, 7)]

In [3]:
scheduler.states[-1].describe()

,Arrival,Burst,Priority,Remaining,Completion,Turnaround,Waiting,Response
count,7.000000,7.000000,7.0,7.0,7.000000,7.000000,7.000000,7.00000
mean,10.285714,5.571429,0.0,0.0,27.714286,17.428571,11.857143,5.00000
std,17.820534,2.878492,0.0,0.0,14.407339,8.502101,6.817345,3.91578
min,0.000000,2.000000,0.0,0.0,14.000000,7.000000,0.000000,1.00000
25%,1.500000,3.500000,0.0,0.0,19.000000,11.500000,9.000000,1.50000
50%,4.000000,5.000000,0.0,0.0,23.000000,17.000000,13.000000,4.00000
75%,7.500000,7.500000,0.0,0.0,31.000000,22.500000,16.000000,8.50000
max,50.000000,10.000000,0.0,0.0,57.000000,30.000000,20.000000,10.00000

In [5]:
scheduler.states[-1]

,Arrival,Burst,Priority,Remaining,Completion,Turnaround,Waiting,Response,Status
PID,,,,,,,,,
1,0,10,0,0,30,30,20,1,Finished
2,1,4,0,0,18,17,13,2,Finished
3,2,5,0,0,20,18,13,4,Finished
4,4,2,0,0,14,10,8,8,Finished
5,5,8,0,0,32,27,19,9,Finished
6,10,3,0,0,23,13,10,10,Finished
7,50,7,0,0,57,7,0,1,Finished